### ISSUE TITLE
是否可以加前置快捷键呢？

### ISSUE THREAD

**Issue by lyphol** [foreverglory/selection-popup#1]
是否可以增加按下某个按键比如ctrl才能触发划词的选项呢，因为很多情况下可能划词不需要搜索什么的，因为之前用过一个这样扩展，感觉体验稍微好点

**Comment by foreverglory** [comment]
是的，我也正是这样计划的。
正在开发中，骚等几天

**Comment by foreverglory** [comment]
@lyphol 已经增加Ctrl/Control, Alt, Shift 按键及鼠标左,中,右键的划动

**Comment by foreverglory** [comment]
@lyphol 去插件中心直接下载，或者等待自动更新
有问题，请及时反馈，谢谢
